### PR TITLE
add test version of function to locate pycbc live files

### PR DESCRIPTION
**Pull request by ahnitz**
This adds a function to find pycbc live files. It will only work currently for the files available for testing purposes. (which only cover 9/14/15 - 9/16/15). I'm working on getting a shared account for this data, so the basename string will need to be updated when that happens.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
hey @ahnitz, this looks great. Any chance you can take a look at the `test_trigfind.py` script and write up a `unittest` method for the new function?

**Comment by duncanmmacleod** [comment]
so, the test case doesn't run on travis-ci.org because the builder isn't set up to install `lal`, but presuming it runs on LDAS (will test), this looks very nice, thanks.

**Comment by ahnitz** [comment]
That's right. I think re-add the test case skip in this case, as it can't import the gps time conversion functions.

**Comment by ahnitz** [comment]
Doesn't seem to be much I can do about the decrease in coverall score though, since it can't actually test the function in the online travis.

**Comment by duncanmmacleod** [comment]
@ahnitz, I've tested things using the available data on LHO, and it works very well. Can you please correct the trailing whitespace errors in both `test_trigfind.py` and `trigfind/core.py`, then I will be very happy to merge.

**Comment by duncanmmacleod** [comment]
I've been able to test this end-to-end, looks great, thanks @ahnitz.

**Pull request merged**
