### PR TITLE
Added finder for gstlal-idq-features files

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR adds a new finder function for the `gstlal-idq-features` ETG that is newly developed for LIGO.

cc @MyNameIsPatrick.

### CODE REVIEW

**Comment by myNameIsPatrick** [comment]
@duncanmmacleod, sorry for the very late response, I was digging through old emails and found this. I tested both the `find_trigger_files` and `find_gstlal_idq_features_files` and it does what I expect. 

One thing I find a bit strange is that I can put in anything for the `channel` arg and get the same output, I guess that's expected though since the files aren't separated by channel. In order to perform the check, we'd need to check the datasets in the files and see if one matches the channel that is passed in, but maybe for this purpose it's sufficient to leave this out. What do you think?

**Comment by duncanmmacleod** [comment]
Yes, opening the files currently goes beyond the scope of what `gwtrigfind` is designed to do. I wouldn't be totally against functionality to perform this check, but purely as 'optional'.

**Comment by myNameIsPatrick** [comment]
Okay, I think what we have here looks great then.

**Comment by duncanmmacleod** [comment]
Migrated to <https://git.ligo.org/detchar/tools/gwtrigfind/-/merge_requests/28>

**Pull request closed without merging**
